volumes:
  database_volume:
    driver: local   
  llm_volume:
    driver: local
services:
  frontend:
    build: ./src/weblab-ui
    container_name: frontend
    profiles:
      - frontend
    ports:
      - "4200:4200"
    depends_on:
      - backend
    environment:
      - NODE_ENV=development

  backend:
    build: ./src/weblab-backend
    container_name: backend
    profiles:
      - backend
    ports:
      - "8000:8000"

  ollama:
    image: ollama/ollama:latest
    volumes:
      - llm_volume:/root/.ollama
    ports:
      - "11434:11434"
    deploy:
      resources:
        limits:
          cpus: "4"
          memory: "8G"
        reservations:
          cpus: "4"
          memory: "8G"

  database:
    image: mongo:latest
    container_name: database
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - database_volume:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoadmin
      MONGO_INITDB_ROOT_PASSWORD: mongoadmin

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    depends_on:
      - database
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: database
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: changeme
      ME_CONFIG_MONGODB_ADMINUSERNAME: mongoadmin
      ME_CONFIG_MONGODB_ADMINPASSWORD: mongoadmin
      ME_CONFIG_MONGODB_URL: mongodb://mongoadmin:mongoadmin@database:27017/ 
